name: FlowCoordinator
options:
  bundleIdPrefix: xyz.tavares
targets:
  FlowCoordinator:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: Sources/FlowCoordinator
    scheme:
      testTargets:
        - FlowCoordinatorTests
      environmentVariables:
        OS_ACTIVITY_MODE: disable
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
  FlowCoordinatorTests:
    type: bundle.unit-test
    platform: iOS
    sources: Tests
    dependencies:
      - target: FlowCoordinator
    scheme:
      testTargets:
        - FlowCoordinatorTests